#!/usr/bin/env bash
#A while loop that displays nubers from 1-20 with conditions
i="1"
while [ "$i" -le 20 ]; do
	echo "$i"
	case "$i" in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
	esac
	i=$((i + 1))
done;
